from rest_framework import serializers


class ValidateSecretKeySerializer(serializers.Serializer):
    merchant_email = serializers.CharField()
    secret_key = serializers.CharField()


class CreatePayPageSerializer(serializers.Serializer):
    merchant_email = serializers.EmailField()
    secret_key = serializers.CharField()
    site_url = serializers.URLField()
    return_url = serializers.URLField()
    title = serializers.CharField()
    cc_first_name = serializers.CharField()
    cc_last_name = serializers.CharField()
    cc_phone_number = serializers.CharField()
    phone_number = serializers.CharField()
    email = serializers.EmailField()
    products_per_title = serializers.CharField()
    unit_price = serializers.CharField()
    quantity = serializers.CharField()
    other_charges = serializers.FloatField()
    amount = serializers.FloatField()
    discount = serializers.FloatField()
    currency = serializers.CharField()
    reference_no = serializers.CharField()
    ip_customer = serializers.CharField()
    ip_merchant = serializers.CharField()
    billing_address = serializers.CharField()
    state = serializers.CharField()
    city = serializers.CharField()
    postal_code = serializers.CharField()
    country = serializers.CharField()
    shipping_first_name = serializers.CharField()
    shipping_last_name = serializers.CharField()
    address_shipping = serializers.CharField()
    city_shipping = serializers.CharField()
    state_shipping = serializers.CharField()
    postal_code_shipping = serializers.CharField()
    country_shipping = serializers.CharField()
    msg_lang = serializers.CharField()